server {
    listen 80;
    listen [::]:80;
    server_name quant.rubusoo.com;

    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
